export default {
  CHANGE_KEY: "CHANGE_KEY",
  CHANGE_CHORD: "CHANGE_CHORD",
  CHANGE_AUX: "CHANGE_AUX",
  CHANGE_MODE: "CHANGE_MODE",
  CHANGE_NAME_SUB: "CHANGE_NAME_SUB",
  CHANGE_NAME_MAIN: "CHANGE_NAME_MAIN",
  CHANGE_NAME_SUPER: "CHANGE_NAME_SUPER"
};
