export default {
  CHANGE_KEY: "CHANGE_KEY",
  CHANGE_CHORD: "CHANGE_CHORD",
  CHANGE_AUX: "CHANGE_AUX",
  CHANGE_MODE: "CHANGE_MODE",
  // CUSTOM
  CHANGE_FRET: "CHANGE_FRET",
  CHANGE_STRING: "CHANGE_STRING",
  CHANGE_STARTING_FRET: "CHANGE_STARTING_FRET",
  CHANGE_NAME: "CHANGE_NAME",
  CHANGE_AUX_TEXT: "CHANGE_AUX_TEXT",
  CHANGE_SUPER_SYMBOL: "CHANGE_SUPER_SYMBOL",
  CHANGE_EXTRA_NAME: "CHANGE_EXTRA_NAME",
  CHANGE_NOTE_FRET: "CHANGE_NOTE_FRET",
  CHANGE_NOTE_STRING: "CHANGE_NOTE_STRING",
  CHANGE_NOTE_FINGER: "CHANGE_NOTE_FINGER",
  CHANGE_NOTE_BARRE: "CHANGE_NOTE_BARRE",
  ADD_NOTE: "ADD_NOTE",
  DELETE_NOTE: "DELETE_NOTE"
};
